const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Particles,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Tween,
		C3.Behaviors.Fade,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.advert,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Acts.SetLayerParallax,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Cnds.CompareValue,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.ScriptsInEvents.Egame_Event9_Act1,
		C3.ScriptsInEvents.Egame_Event10_Act1,
		C3.ScriptsInEvents.Egame_Event11_Act1,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Exps.Height,
		C3.ScriptsInEvents.Egame_Event19_Act5,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Particles.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Exps.ColorValue,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.Play,
		C3.ScriptsInEvents.Egame_Event23_Act10,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.ScriptsInEvents.Egame_Event25_Act5,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.ScriptsInEvents.Egame_Event33_Act2,
		C3.ScriptsInEvents.Egame_Event33_Act8,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.ScriptsInEvents.Egame_Event36_Act5,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Exps.Y
	];
};
self.C3_JsPropNameTable = [
	{Color: 0},
	{PerfectPointUID: 0},
	{Tile: 0},
	{PerfectPoint: 0},
	{ColorBar: 0},
	{LastY: 0},
	{LeftCountForNextColorBar: 0},
	{LastMouseX: 0},
	{GameManager: 0},
	{ScrollTo: 0},
	{Camera: 0},
	{Velocity: 0},
	{JumpSpeed: 0},
	{TargetX: 0},
	{Player: 0},
	{Keyboard: 0},
	{Touch: 0},
	{JumpParticleEffect: 0},
	{DieEffect: 0},
	{touch_bar: 0},
	{Sine: 0},
	{hand_icon: 0},
	{favBtn: 0},
	{SoundBtn: 0},
	{main_menu_bg: 0},
	{Sprite2: 0},
	{best_txt: 0},
	{score_txt: 0},
	{game_over_bg: 0},
	{tap_to_restart_text: 0},
	{LocalStorage: 0},
	{PerfectParticleEffect: 0},
	{Tween: 0},
	{Fade: 0},
	{score_effect: 0},
	{Audio: 0},
	{Browser: 0},
	{MobileAdvert: 0},
	{best_txt2: 0},
	{BallJumpOvershoot: 0},
	{VTileDistance: 0},
	{MinGravity: 0},
	{MaxGravity: 0},
	{GravityIncreaseRate: 0},
	{CurrentGravity: 0},
	{Best: 0},
	{Temp: 0},
	{Score: 0},
	{GameState: 0},
	{StoreUrl: 0},
	{Sound: 0},
	{ContinuePerfectCount: 0},
	{admobInterstialId: 0},
	{CameraOffset: 0}
];

self.InstanceType = {
	Tile: class extends self.ISpriteInstance {},
	PerfectPoint: class extends self.ISpriteInstance {},
	ColorBar: class extends self.ISpriteInstance {},
	GameManager: class extends self.ISpriteInstance {},
	Camera: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	JumpParticleEffect: class extends self.IParticlesInstance {},
	DieEffect: class extends self.IParticlesInstance {},
	touch_bar: class extends self.ISpriteInstance {},
	hand_icon: class extends self.ISpriteInstance {},
	favBtn: class extends self.ISpriteInstance {},
	SoundBtn: class extends self.ISpriteInstance {},
	main_menu_bg: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	best_txt: class extends self.ITextInstance {},
	score_txt: class extends self.ITextInstance {},
	game_over_bg: class extends self.ISpriteInstance {},
	tap_to_restart_text: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {},
	PerfectParticleEffect: class extends self.IParticlesInstance {},
	score_effect: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	MobileAdvert: class extends self.IInstance {},
	best_txt2: class extends self.ITextInstance {}
}